"""Initial migration

Revision ID: 4efdcf113b6d
Revises: 20260527_0001
Create Date: 2025-03-08 18:54:19.370558

Legacy branch anchor; schema is created in 20260527_0001.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4efdcf113b6d'
down_revision: Union[str, None] = '20260527_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
